/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Fri Nov  3 09:46:45 2023
 * --------------------------------------------------------
 *
 */
#ifndef USER_ALL_ID_h
#define USER_ALL_ID_h

// ============================================================ //


// joint

#define T1_Frame_id 1
#define T2_Frame_id 2
#define T3_Frame_id 3
#define R3_Frame_id 4
#define R1_Frame_id 5
#define R2_Frame_id 6
#define T1_Box_id 7
#define T3_Box_id 8
#define R2_Box_id 9
#define R2_Fork_id 10
#define R3_Fork_id 11
#define R2_FrontWheel_id 12
#define R2_RearWheel_id 13
#define Joint_7_id 14
#define Joint_0_id 15
#define R1_Arm_l_id 16
#define R2_Arm_l_id 17
#define R3_Arm_l_id 18
#define R2_Forearm_l_id 19
#define Joint_5_id 20
#define R1_Arm_r_id 21
#define R2_Arm_r_id 22
#define R3_Arm_r_id 23
#define R2_Forearm_r_id 24
#define Joint_6_id 25
#define R2_head_id 26
#define R2_UpperLeg_l_id 27
#define R2_LowerLeg_l_id 28
#define R2_Foot_l_id 29
#define R2_UpperLeg_r_id 30
#define R2_LowerLeg_r_id 31
#define R2_Foot_r_id 32

static char *mbs_joints_name[] = {
	"ORIGIN",
	"T1_Frame",
	"T2_Frame",
	"T3_Frame",
	"R3_Frame",
	"R1_Frame",
	"R2_Frame",
	"T1_Box",
	"T3_Box",
	"R2_Box",
	"R2_Fork",
	"R3_Fork",
	"R2_FrontWheel",
	"R2_RearWheel",
	"Joint_7",
	"Joint_0",
	"R1_Arm_l",
	"R2_Arm_l",
	"R3_Arm_l",
	"R2_Forearm_l",
	"Joint_5",
	"R1_Arm_r",
	"R2_Arm_r",
	"R3_Arm_r",
	"R2_Forearm_r",
	"Joint_6",
	"R2_head",
	"R2_UpperLeg_l",
	"R2_LowerLeg_l",
	"R2_Foot_l",
	"R2_UpperLeg_r",
	"R2_LowerLeg_r",
	"R2_Foot_r"
	};

// body

#define Frame_id 6
#define Box_id 9
#define Fork_id 11
#define FrontWheel_id 12
#define RearWheel_id 13
#define Pelvis_id 14
#define RiderTrunk_id 15
#define Arm_l_id 18
#define Forearm_l_id 19
#define Hand_l_id 20
#define Arm_r_id 23
#define Forearm_r_id 24
#define Hand_r_id 25
#define Head_id 26
#define UpperLeg_l_id 27
#define LowerLeg_l_id 28
#define Foot_l_id 29
#define UpperLeg_r_id 30
#define LowerLeg_r_id 31
#define Foot_r_id 32

static char *mbs_bodies_name[] = {
	"INVALID BODY ID : this is the base body 0",
	"Frame",
	"Box",
	"Fork",
	"FrontWheel",
	"RearWheel",
	"Pelvis",
	"RiderTrunk",
	"Arm_l",
	"Forearm_l",
	"Hand_l",
	"Arm_r",
	"Forearm_r",
	"Hand_r",
	"Head",
	"UpperLeg_l",
	"LowerLeg_l",
	"Foot_l",
	"UpperLeg_r",
	"LowerLeg_r",
	"Foot_r"
	};

// point

#define Frame_to_front_id 1
#define Frame_to_rear_id 2
#define Frame_to_saddle_id 3
#define Frame_to_IMU_id 4
#define Fork_to_front_wheel_id 5
//#define FrontWheel_origin_id 6
//#define RearWheel_origin_id 7
#define Pelvis_Point_0_id 8
#define Pelvis_to_leg_l_id 9
#define Pelvis_to_leg_r_id 10
#define RiderTrunk_to_arm_l_id 11
#define RiderTrunk_to_arm_r_id 12
#define RiderTrunk_to_head_id 13
#define Arm_l_to_forearm_l_id 14
#define Forearm_l_to_hand_l_id 15
#define Arm_r_Point_0_id 16
#define Forearm_r_Point_0_id 17
#define UpperLeg_l_to_knee_id 18
#define LowerLeg_l_to_ankle_id 19
#define UpperLeg_r_to_knee_id 20
#define LowerLeg_r_to_ankle_id 21


// sensor

#define IMU_id 1

static char *mbs_sensors_name[] = {
	"INVALID SENSOR ID: 0",
	"IMU"
	};

// extforce

#define xFrc_wheel_front_id 1
#define xFrc_wheel_rear_id 2

static char *mbs_extforces_name[] = {
	"INVALID EXTFORCE ID: 0",
	"xFrc_wheel_front",
	"xFrc_wheel_rear"
	};

// links



// links 3D



// Rods



// ============================================================ //

# endif
