/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Thu Nov  7 16:19:01 2019
 * --------------------------------------------------------
 *
 */
#ifndef USER_HARD_PARAM_h
#define USER_HARD_PARAM_h

// ============================================================ //


// gravity
#define G_3 -9.81

// mass
#define M_6 85
#define M_8 4
#define M_9 3
#define M_10 2

// center of mass
#define L_1_8 0.0261
#define L_3_8 -0.2188

// inertia
#define IN_1_6 9.2
#define IN_3_6 -2.4
#define IN_5_6 11
#define IN_9_6 2.8
#define IN_1_8 0.0584134
#define IN_3_8 -0.00911921
#define IN_5_8 0.06
#define IN_9_8 0.00758662
#define IN_1_9 0.1405
#define IN_5_9 0.28
#define IN_9_9 0.1405
#define IN_1_10 0.0603
#define IN_5_10 0.12
#define IN_9_10 0.0603

// body point
#define DPT_1_1 0.507572
#define DPT_1_2 -0.3
#define DPT_3_2 -0.6
#define DPT_1_3 0.0321
#define DPT_3_3 -0.5887
#define DPT_3_5 -0.35
#define DPT_3_7 -0.3

// ============================================================ //

# endif
