/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Mon Nov 18 13:52:09 2024
 * --------------------------------------------------------
 *
 */
#include "mbs_path.h"
#include "user_model.h"
#include "mbs_binder_public.h"
#include "mbs_loader.h"
#include "useful_functions.h"
#include "mbs_message.h"
#include "lut.h"
#include <math.h>
#include <float.h>

// ============================================================ //


UserModel* mbs_new_user_model() 
{
    UserModel* um;
    um = (UserModel*)malloc(sizeof(UserModel));
    um->rider.K_phi = 0.0;
    um->rider.K_phid = 0.0;
    um->rider.K_y = 0.0;
    um->rider.K_yd = 0.0;
    um->rider.K_delta = 0.0;
    um->rider.K_deltad = 0.0;
    um->rider.phi_max = 0.0;
 
    um->tyre.K = 0.0;
    um->tyre.C = 0.0;
    um->tyre.R0 = 0.0;
    um->tyre.CFx = 0.0;
    um->tyre.CFy = 0.0;
    um->tyre.CMz_ratio = 0.0;
    um->tyre.flag_saturation = 0;
    um->tyre.friction = 0.0;
 
    um->cargo.flag_load_case = 0;
    um->cargo.load_at_front_m = 0.0;
    um->cargo.load_at_front_x = 0.0;
    um->cargo.load_at_front_z = 0.0;
    um->cargo.load_at_front_alpha = 0.0;
    um->cargo.load_at_back_m = 0.0;
    um->cargo.load_at_back_x = 0.0;
    um->cargo.load_at_back_z = 0.0;
    um->cargo.load_at_back_alpha = 0.0;
 
    um->global.speed = 0.0;
    um->global.tf = 0.0;
    um->global.flag_bilateral_normal_force = 0.0;
    um->global.flag_tangential_force = 0.0;
    um->global.res_name = NULL;
    um->global.res_path = NULL;
 
    um->trajectory.lateral_offset = 0.0;
    um->trajectory.dist_go_to_left = 0.0;
    um->trajectory.dist_go_to_right = 0.0;
 
    um->ground.flag_ground = 0;
    um->ground.ground_profile = NULL;
 
    um->utility.sens_IMU = NULL;
 
    return um;
}

void mbs_delete_user_model(UserModel* um) 
{
    free(um->global.res_name);
    free(um->global.res_path);
    free(um);
}

 void mbs_load_user_model(MbsInfos* mbs_infos, UserModel* um) 
{
    int ind_state_value = 1;

    um->rider.K_phi = mbs_infos->user_models->user_model_list[0]->parameter_list[0]->value_list[1];
    um->rider.K_phid = mbs_infos->user_models->user_model_list[0]->parameter_list[1]->value_list[1];
    um->rider.K_y = mbs_infos->user_models->user_model_list[0]->parameter_list[2]->value_list[1];
    um->rider.K_yd = mbs_infos->user_models->user_model_list[0]->parameter_list[3]->value_list[1];
    um->rider.K_delta = mbs_infos->user_models->user_model_list[0]->parameter_list[4]->value_list[1];
    um->rider.K_deltad = mbs_infos->user_models->user_model_list[0]->parameter_list[5]->value_list[1];
    um->rider.phi_max = mbs_infos->user_models->user_model_list[0]->parameter_list[6]->value_list[1];
 
    um->tyre.K = mbs_infos->user_models->user_model_list[1]->parameter_list[0]->value_list[1];
    um->tyre.C = mbs_infos->user_models->user_model_list[1]->parameter_list[1]->value_list[1];
    um->tyre.R0 = mbs_infos->user_models->user_model_list[1]->parameter_list[2]->value_list[1];
    um->tyre.CFx = mbs_infos->user_models->user_model_list[1]->parameter_list[3]->value_list[1];
    um->tyre.CFy = mbs_infos->user_models->user_model_list[1]->parameter_list[4]->value_list[1];
    um->tyre.CMz_ratio = mbs_infos->user_models->user_model_list[1]->parameter_list[5]->value_list[1];
    um->tyre.flag_saturation = (int)lround(mbs_infos->user_models->user_model_list[1]->parameter_list[6]->value_list[1]);
    um->tyre.friction = mbs_infos->user_models->user_model_list[1]->parameter_list[7]->value_list[1];
 
    um->cargo.flag_load_case = (int)lround(mbs_infos->user_models->user_model_list[2]->parameter_list[0]->value_list[1]);
    um->cargo.load_at_front_m = mbs_infos->user_models->user_model_list[2]->parameter_list[1]->value_list[1];
    um->cargo.load_at_front_x = mbs_infos->user_models->user_model_list[2]->parameter_list[2]->value_list[1];
    um->cargo.load_at_front_z = mbs_infos->user_models->user_model_list[2]->parameter_list[3]->value_list[1];
    um->cargo.load_at_front_alpha = mbs_infos->user_models->user_model_list[2]->parameter_list[4]->value_list[1];
    um->cargo.load_at_back_m = mbs_infos->user_models->user_model_list[2]->parameter_list[5]->value_list[1];
    um->cargo.load_at_back_x = mbs_infos->user_models->user_model_list[2]->parameter_list[6]->value_list[1];
    um->cargo.load_at_back_z = mbs_infos->user_models->user_model_list[2]->parameter_list[7]->value_list[1];
    um->cargo.load_at_back_alpha = mbs_infos->user_models->user_model_list[2]->parameter_list[8]->value_list[1];
 
    um->global.speed = mbs_infos->user_models->user_model_list[3]->parameter_list[0]->value_list[1];
    um->global.tf = mbs_infos->user_models->user_model_list[3]->parameter_list[1]->value_list[1];
    um->global.flag_bilateral_normal_force = mbs_infos->user_models->user_model_list[3]->parameter_list[2]->value_list[1];
    um->global.flag_tangential_force = mbs_infos->user_models->user_model_list[3]->parameter_list[3]->value_list[1];
    um->global.res_name = get_char_cpy(mbs_infos->user_models->user_model_list[3]->parameter_list[4]->string_name);
    um->global.res_path = get_char_cpy(mbs_infos->user_models->user_model_list[3]->parameter_list[5]->string_name);
 
    um->trajectory.lateral_offset = mbs_infos->user_models->user_model_list[4]->parameter_list[0]->value_list[1];
    um->trajectory.dist_go_to_left = mbs_infos->user_models->user_model_list[4]->parameter_list[1]->value_list[1];
    um->trajectory.dist_go_to_right = mbs_infos->user_models->user_model_list[4]->parameter_list[2]->value_list[1];
 
    um->ground.flag_ground = (int)lround(mbs_infos->user_models->user_model_list[5]->parameter_list[0]->value_list[1]);
 
 
}

 void mbs_bind_user_model(MbsInfos* mbs_infos, UserModel* um) 
{
    mbs_infos->user_models->user_model_list[0]->parameter_list[0]->val_ptr = &um->rider.K_phi;
    mbs_infos->user_models->user_model_list[0]->parameter_list[1]->val_ptr = &um->rider.K_phid;
    mbs_infos->user_models->user_model_list[0]->parameter_list[2]->val_ptr = &um->rider.K_y;
    mbs_infos->user_models->user_model_list[0]->parameter_list[3]->val_ptr = &um->rider.K_yd;
    mbs_infos->user_models->user_model_list[0]->parameter_list[4]->val_ptr = &um->rider.K_delta;
    mbs_infos->user_models->user_model_list[0]->parameter_list[5]->val_ptr = &um->rider.K_deltad;
    mbs_infos->user_models->user_model_list[0]->parameter_list[6]->val_ptr = &um->rider.phi_max;
 
    mbs_infos->user_models->user_model_list[1]->parameter_list[0]->val_ptr = &um->tyre.K;
    mbs_infos->user_models->user_model_list[1]->parameter_list[1]->val_ptr = &um->tyre.C;
    mbs_infos->user_models->user_model_list[1]->parameter_list[2]->val_ptr = &um->tyre.R0;
    mbs_infos->user_models->user_model_list[1]->parameter_list[3]->val_ptr = &um->tyre.CFx;
    mbs_infos->user_models->user_model_list[1]->parameter_list[4]->val_ptr = &um->tyre.CFy;
    mbs_infos->user_models->user_model_list[1]->parameter_list[5]->val_ptr = &um->tyre.CMz_ratio;
    mbs_infos->user_models->user_model_list[1]->parameter_list[6]->val_ptr = &um->tyre.flag_saturation;
    mbs_infos->user_models->user_model_list[1]->parameter_list[7]->val_ptr = &um->tyre.friction;
 
    mbs_infos->user_models->user_model_list[2]->parameter_list[0]->val_ptr = &um->cargo.flag_load_case;
    mbs_infos->user_models->user_model_list[2]->parameter_list[1]->val_ptr = &um->cargo.load_at_front_m;
    mbs_infos->user_models->user_model_list[2]->parameter_list[2]->val_ptr = &um->cargo.load_at_front_x;
    mbs_infos->user_models->user_model_list[2]->parameter_list[3]->val_ptr = &um->cargo.load_at_front_z;
    mbs_infos->user_models->user_model_list[2]->parameter_list[4]->val_ptr = &um->cargo.load_at_front_alpha;
    mbs_infos->user_models->user_model_list[2]->parameter_list[5]->val_ptr = &um->cargo.load_at_back_m;
    mbs_infos->user_models->user_model_list[2]->parameter_list[6]->val_ptr = &um->cargo.load_at_back_x;
    mbs_infos->user_models->user_model_list[2]->parameter_list[7]->val_ptr = &um->cargo.load_at_back_z;
    mbs_infos->user_models->user_model_list[2]->parameter_list[8]->val_ptr = &um->cargo.load_at_back_alpha;
 
    mbs_infos->user_models->user_model_list[3]->parameter_list[0]->val_ptr = &um->global.speed;
    mbs_infos->user_models->user_model_list[3]->parameter_list[1]->val_ptr = &um->global.tf;
    mbs_infos->user_models->user_model_list[3]->parameter_list[2]->val_ptr = &um->global.flag_bilateral_normal_force;
    mbs_infos->user_models->user_model_list[3]->parameter_list[3]->val_ptr = &um->global.flag_tangential_force;
    mbs_infos->user_models->user_model_list[3]->parameter_list[4]->val_ptr = &um->global.res_name;
    mbs_infos->user_models->user_model_list[3]->parameter_list[5]->val_ptr = &um->global.res_path;
 
    mbs_infos->user_models->user_model_list[4]->parameter_list[0]->val_ptr = &um->trajectory.lateral_offset;
    mbs_infos->user_models->user_model_list[4]->parameter_list[1]->val_ptr = &um->trajectory.dist_go_to_left;
    mbs_infos->user_models->user_model_list[4]->parameter_list[2]->val_ptr = &um->trajectory.dist_go_to_right;
 
    mbs_infos->user_models->user_model_list[5]->parameter_list[0]->val_ptr = &um->ground.flag_ground;
    mbs_infos->user_models->user_model_list[5]->parameter_list[1]->val_ptr = &um->ground.ground_profile;
 
    mbs_infos->user_models->user_model_list[6]->parameter_list[0]->val_ptr = &um->utility.sens_IMU;
 
}
 
 void mbs_print_user_model(UserModel* um) 
{

    printf("user_model->rider.K_phi=%f\n", um->rider.K_phi);
    printf("user_model->rider.K_phid=%f\n", um->rider.K_phid);
    printf("user_model->rider.K_y=%f\n", um->rider.K_y);
    printf("user_model->rider.K_yd=%f\n", um->rider.K_yd);
    printf("user_model->rider.K_delta=%f\n", um->rider.K_delta);
    printf("user_model->rider.K_deltad=%f\n", um->rider.K_deltad);
    printf("user_model->rider.phi_max=%f\n", um->rider.phi_max);
 
    printf("user_model->tyre.K=%f\n", um->tyre.K);
    printf("user_model->tyre.C=%f\n", um->tyre.C);
    printf("user_model->tyre.R0=%f\n", um->tyre.R0);
    printf("user_model->tyre.CFx=%f\n", um->tyre.CFx);
    printf("user_model->tyre.CFy=%f\n", um->tyre.CFy);
    printf("user_model->tyre.CMz_ratio=%f\n", um->tyre.CMz_ratio);
    printf("user_model->tyre.flag_saturation=%d\n", um->tyre.flag_saturation);
    printf("user_model->tyre.friction=%f\n", um->tyre.friction);
 
    printf("user_model->cargo.flag_load_case=%d\n", um->cargo.flag_load_case);
    printf("user_model->cargo.load_at_front_m=%f\n", um->cargo.load_at_front_m);
    printf("user_model->cargo.load_at_front_x=%f\n", um->cargo.load_at_front_x);
    printf("user_model->cargo.load_at_front_z=%f\n", um->cargo.load_at_front_z);
    printf("user_model->cargo.load_at_front_alpha=%f\n", um->cargo.load_at_front_alpha);
    printf("user_model->cargo.load_at_back_m=%f\n", um->cargo.load_at_back_m);
    printf("user_model->cargo.load_at_back_x=%f\n", um->cargo.load_at_back_x);
    printf("user_model->cargo.load_at_back_z=%f\n", um->cargo.load_at_back_z);
    printf("user_model->cargo.load_at_back_alpha=%f\n", um->cargo.load_at_back_alpha);
 
    printf("user_model->global.speed=%f\n", um->global.speed);
    printf("user_model->global.tf=%f\n", um->global.tf);
    printf("user_model->global.flag_bilateral_normal_force=%f\n", um->global.flag_bilateral_normal_force);
    printf("user_model->global.flag_tangential_force=%f\n", um->global.flag_tangential_force);
    printf("user_model->global.res_name=%s\n", um->global.res_name);
    printf("user_model->global.res_path=%s\n", um->global.res_path);
 
    printf("user_model->trajectory.lateral_offset=%f\n", um->trajectory.lateral_offset);
    printf("user_model->trajectory.dist_go_to_left=%f\n", um->trajectory.dist_go_to_left);
    printf("user_model->trajectory.dist_go_to_right=%f\n", um->trajectory.dist_go_to_right);
 
    printf("user_model->ground.flag_ground=%d\n", um->ground.flag_ground);
    printf("user_model->ground.ground_profile : structure content will not be printed here \n");
 
    printf("user_model->utility.sens_IMU : structure content will not be printed here \n");
 
}
 
void mbs_get_user_model_size(int *n_user_model) 
{
    *n_user_model  = 7; 
}
 
void mbs_get_user_model_list(int *user_model_list) 
{
    user_model_list[1]  = 7; 
    user_model_list[2]  = 8; 
    user_model_list[3]  = 9; 
    user_model_list[4]  = 6; 
    user_model_list[5]  = 3; 
    user_model_list[6]  = 2; 
    user_model_list[7]  = 1; 

}

void mbs_save_um(FILE* stream, UserModel* um)
{
    if (isnan(um->rider.K_phi)) { fprintf(stream, "         s->user_model->rider.K_phi = NAN; \n");}
    else if (isinf(um->rider.K_phi)) { fprintf(stream, "        s->user_model->rider.K_phi = %d * INFINITY; \n", isinf(um->rider.K_phi));}
    else { fprintf(stream, "        s->user_model->rider.K_phi = %.*e;\n", DBL_DECIMAL_DIG - 1, um->rider.K_phi);}
    if (isnan(um->rider.K_phid)) { fprintf(stream, "         s->user_model->rider.K_phid = NAN; \n");}
    else if (isinf(um->rider.K_phid)) { fprintf(stream, "        s->user_model->rider.K_phid = %d * INFINITY; \n", isinf(um->rider.K_phid));}
    else { fprintf(stream, "        s->user_model->rider.K_phid = %.*e;\n", DBL_DECIMAL_DIG - 1, um->rider.K_phid);}
    if (isnan(um->rider.K_y)) { fprintf(stream, "         s->user_model->rider.K_y = NAN; \n");}
    else if (isinf(um->rider.K_y)) { fprintf(stream, "        s->user_model->rider.K_y = %d * INFINITY; \n", isinf(um->rider.K_y));}
    else { fprintf(stream, "        s->user_model->rider.K_y = %.*e;\n", DBL_DECIMAL_DIG - 1, um->rider.K_y);}
    if (isnan(um->rider.K_yd)) { fprintf(stream, "         s->user_model->rider.K_yd = NAN; \n");}
    else if (isinf(um->rider.K_yd)) { fprintf(stream, "        s->user_model->rider.K_yd = %d * INFINITY; \n", isinf(um->rider.K_yd));}
    else { fprintf(stream, "        s->user_model->rider.K_yd = %.*e;\n", DBL_DECIMAL_DIG - 1, um->rider.K_yd);}
    if (isnan(um->rider.K_delta)) { fprintf(stream, "         s->user_model->rider.K_delta = NAN; \n");}
    else if (isinf(um->rider.K_delta)) { fprintf(stream, "        s->user_model->rider.K_delta = %d * INFINITY; \n", isinf(um->rider.K_delta));}
    else { fprintf(stream, "        s->user_model->rider.K_delta = %.*e;\n", DBL_DECIMAL_DIG - 1, um->rider.K_delta);}
    if (isnan(um->rider.K_deltad)) { fprintf(stream, "         s->user_model->rider.K_deltad = NAN; \n");}
    else if (isinf(um->rider.K_deltad)) { fprintf(stream, "        s->user_model->rider.K_deltad = %d * INFINITY; \n", isinf(um->rider.K_deltad));}
    else { fprintf(stream, "        s->user_model->rider.K_deltad = %.*e;\n", DBL_DECIMAL_DIG - 1, um->rider.K_deltad);}
    if (isnan(um->rider.phi_max)) { fprintf(stream, "         s->user_model->rider.phi_max = NAN; \n");}
    else if (isinf(um->rider.phi_max)) { fprintf(stream, "        s->user_model->rider.phi_max = %d * INFINITY; \n", isinf(um->rider.phi_max));}
    else { fprintf(stream, "        s->user_model->rider.phi_max = %.*e;\n", DBL_DECIMAL_DIG - 1, um->rider.phi_max);}
 
    if (isnan(um->tyre.K)) { fprintf(stream, "         s->user_model->tyre.K = NAN; \n");}
    else if (isinf(um->tyre.K)) { fprintf(stream, "        s->user_model->tyre.K = %d * INFINITY; \n", isinf(um->tyre.K));}
    else { fprintf(stream, "        s->user_model->tyre.K = %.*e;\n", DBL_DECIMAL_DIG - 1, um->tyre.K);}
    if (isnan(um->tyre.C)) { fprintf(stream, "         s->user_model->tyre.C = NAN; \n");}
    else if (isinf(um->tyre.C)) { fprintf(stream, "        s->user_model->tyre.C = %d * INFINITY; \n", isinf(um->tyre.C));}
    else { fprintf(stream, "        s->user_model->tyre.C = %.*e;\n", DBL_DECIMAL_DIG - 1, um->tyre.C);}
    if (isnan(um->tyre.R0)) { fprintf(stream, "         s->user_model->tyre.R0 = NAN; \n");}
    else if (isinf(um->tyre.R0)) { fprintf(stream, "        s->user_model->tyre.R0 = %d * INFINITY; \n", isinf(um->tyre.R0));}
    else { fprintf(stream, "        s->user_model->tyre.R0 = %.*e;\n", DBL_DECIMAL_DIG - 1, um->tyre.R0);}
    if (isnan(um->tyre.CFx)) { fprintf(stream, "         s->user_model->tyre.CFx = NAN; \n");}
    else if (isinf(um->tyre.CFx)) { fprintf(stream, "        s->user_model->tyre.CFx = %d * INFINITY; \n", isinf(um->tyre.CFx));}
    else { fprintf(stream, "        s->user_model->tyre.CFx = %.*e;\n", DBL_DECIMAL_DIG - 1, um->tyre.CFx);}
    if (isnan(um->tyre.CFy)) { fprintf(stream, "         s->user_model->tyre.CFy = NAN; \n");}
    else if (isinf(um->tyre.CFy)) { fprintf(stream, "        s->user_model->tyre.CFy = %d * INFINITY; \n", isinf(um->tyre.CFy));}
    else { fprintf(stream, "        s->user_model->tyre.CFy = %.*e;\n", DBL_DECIMAL_DIG - 1, um->tyre.CFy);}
    if (isnan(um->tyre.CMz_ratio)) { fprintf(stream, "         s->user_model->tyre.CMz_ratio = NAN; \n");}
    else if (isinf(um->tyre.CMz_ratio)) { fprintf(stream, "        s->user_model->tyre.CMz_ratio = %d * INFINITY; \n", isinf(um->tyre.CMz_ratio));}
    else { fprintf(stream, "        s->user_model->tyre.CMz_ratio = %.*e;\n", DBL_DECIMAL_DIG - 1, um->tyre.CMz_ratio);}
    fprintf(stream, "        s->user_model->tyre.flag_saturation=%d;\n", um->tyre.flag_saturation);
    if (isnan(um->tyre.friction)) { fprintf(stream, "         s->user_model->tyre.friction = NAN; \n");}
    else if (isinf(um->tyre.friction)) { fprintf(stream, "        s->user_model->tyre.friction = %d * INFINITY; \n", isinf(um->tyre.friction));}
    else { fprintf(stream, "        s->user_model->tyre.friction = %.*e;\n", DBL_DECIMAL_DIG - 1, um->tyre.friction);}
 
    fprintf(stream, "        s->user_model->cargo.flag_load_case=%d;\n", um->cargo.flag_load_case);
    if (isnan(um->cargo.load_at_front_m)) { fprintf(stream, "         s->user_model->cargo.load_at_front_m = NAN; \n");}
    else if (isinf(um->cargo.load_at_front_m)) { fprintf(stream, "        s->user_model->cargo.load_at_front_m = %d * INFINITY; \n", isinf(um->cargo.load_at_front_m));}
    else { fprintf(stream, "        s->user_model->cargo.load_at_front_m = %.*e;\n", DBL_DECIMAL_DIG - 1, um->cargo.load_at_front_m);}
    if (isnan(um->cargo.load_at_front_x)) { fprintf(stream, "         s->user_model->cargo.load_at_front_x = NAN; \n");}
    else if (isinf(um->cargo.load_at_front_x)) { fprintf(stream, "        s->user_model->cargo.load_at_front_x = %d * INFINITY; \n", isinf(um->cargo.load_at_front_x));}
    else { fprintf(stream, "        s->user_model->cargo.load_at_front_x = %.*e;\n", DBL_DECIMAL_DIG - 1, um->cargo.load_at_front_x);}
    if (isnan(um->cargo.load_at_front_z)) { fprintf(stream, "         s->user_model->cargo.load_at_front_z = NAN; \n");}
    else if (isinf(um->cargo.load_at_front_z)) { fprintf(stream, "        s->user_model->cargo.load_at_front_z = %d * INFINITY; \n", isinf(um->cargo.load_at_front_z));}
    else { fprintf(stream, "        s->user_model->cargo.load_at_front_z = %.*e;\n", DBL_DECIMAL_DIG - 1, um->cargo.load_at_front_z);}
    if (isnan(um->cargo.load_at_front_alpha)) { fprintf(stream, "         s->user_model->cargo.load_at_front_alpha = NAN; \n");}
    else if (isinf(um->cargo.load_at_front_alpha)) { fprintf(stream, "        s->user_model->cargo.load_at_front_alpha = %d * INFINITY; \n", isinf(um->cargo.load_at_front_alpha));}
    else { fprintf(stream, "        s->user_model->cargo.load_at_front_alpha = %.*e;\n", DBL_DECIMAL_DIG - 1, um->cargo.load_at_front_alpha);}
    if (isnan(um->cargo.load_at_back_m)) { fprintf(stream, "         s->user_model->cargo.load_at_back_m = NAN; \n");}
    else if (isinf(um->cargo.load_at_back_m)) { fprintf(stream, "        s->user_model->cargo.load_at_back_m = %d * INFINITY; \n", isinf(um->cargo.load_at_back_m));}
    else { fprintf(stream, "        s->user_model->cargo.load_at_back_m = %.*e;\n", DBL_DECIMAL_DIG - 1, um->cargo.load_at_back_m);}
    if (isnan(um->cargo.load_at_back_x)) { fprintf(stream, "         s->user_model->cargo.load_at_back_x = NAN; \n");}
    else if (isinf(um->cargo.load_at_back_x)) { fprintf(stream, "        s->user_model->cargo.load_at_back_x = %d * INFINITY; \n", isinf(um->cargo.load_at_back_x));}
    else { fprintf(stream, "        s->user_model->cargo.load_at_back_x = %.*e;\n", DBL_DECIMAL_DIG - 1, um->cargo.load_at_back_x);}
    if (isnan(um->cargo.load_at_back_z)) { fprintf(stream, "         s->user_model->cargo.load_at_back_z = NAN; \n");}
    else if (isinf(um->cargo.load_at_back_z)) { fprintf(stream, "        s->user_model->cargo.load_at_back_z = %d * INFINITY; \n", isinf(um->cargo.load_at_back_z));}
    else { fprintf(stream, "        s->user_model->cargo.load_at_back_z = %.*e;\n", DBL_DECIMAL_DIG - 1, um->cargo.load_at_back_z);}
    if (isnan(um->cargo.load_at_back_alpha)) { fprintf(stream, "         s->user_model->cargo.load_at_back_alpha = NAN; \n");}
    else if (isinf(um->cargo.load_at_back_alpha)) { fprintf(stream, "        s->user_model->cargo.load_at_back_alpha = %d * INFINITY; \n", isinf(um->cargo.load_at_back_alpha));}
    else { fprintf(stream, "        s->user_model->cargo.load_at_back_alpha = %.*e;\n", DBL_DECIMAL_DIG - 1, um->cargo.load_at_back_alpha);}
 
    if (isnan(um->global.speed)) { fprintf(stream, "         s->user_model->global.speed = NAN; \n");}
    else if (isinf(um->global.speed)) { fprintf(stream, "        s->user_model->global.speed = %d * INFINITY; \n", isinf(um->global.speed));}
    else { fprintf(stream, "        s->user_model->global.speed = %.*e;\n", DBL_DECIMAL_DIG - 1, um->global.speed);}
    if (isnan(um->global.tf)) { fprintf(stream, "         s->user_model->global.tf = NAN; \n");}
    else if (isinf(um->global.tf)) { fprintf(stream, "        s->user_model->global.tf = %d * INFINITY; \n", isinf(um->global.tf));}
    else { fprintf(stream, "        s->user_model->global.tf = %.*e;\n", DBL_DECIMAL_DIG - 1, um->global.tf);}
    if (isnan(um->global.flag_bilateral_normal_force)) { fprintf(stream, "         s->user_model->global.flag_bilateral_normal_force = NAN; \n");}
    else if (isinf(um->global.flag_bilateral_normal_force)) { fprintf(stream, "        s->user_model->global.flag_bilateral_normal_force = %d * INFINITY; \n", isinf(um->global.flag_bilateral_normal_force));}
    else { fprintf(stream, "        s->user_model->global.flag_bilateral_normal_force = %.*e;\n", DBL_DECIMAL_DIG - 1, um->global.flag_bilateral_normal_force);}
    if (isnan(um->global.flag_tangential_force)) { fprintf(stream, "         s->user_model->global.flag_tangential_force = NAN; \n");}
    else if (isinf(um->global.flag_tangential_force)) { fprintf(stream, "        s->user_model->global.flag_tangential_force = %d * INFINITY; \n", isinf(um->global.flag_tangential_force));}
    else { fprintf(stream, "        s->user_model->global.flag_tangential_force = %.*e;\n", DBL_DECIMAL_DIG - 1, um->global.flag_tangential_force);}
    fprintf(stream, "        s->user_model->global.res_name=%s;\n", um->global.res_name);
    fprintf(stream, "        s->user_model->global.res_path=%s;\n", um->global.res_path);
 
    if (isnan(um->trajectory.lateral_offset)) { fprintf(stream, "         s->user_model->trajectory.lateral_offset = NAN; \n");}
    else if (isinf(um->trajectory.lateral_offset)) { fprintf(stream, "        s->user_model->trajectory.lateral_offset = %d * INFINITY; \n", isinf(um->trajectory.lateral_offset));}
    else { fprintf(stream, "        s->user_model->trajectory.lateral_offset = %.*e;\n", DBL_DECIMAL_DIG - 1, um->trajectory.lateral_offset);}
    if (isnan(um->trajectory.dist_go_to_left)) { fprintf(stream, "         s->user_model->trajectory.dist_go_to_left = NAN; \n");}
    else if (isinf(um->trajectory.dist_go_to_left)) { fprintf(stream, "        s->user_model->trajectory.dist_go_to_left = %d * INFINITY; \n", isinf(um->trajectory.dist_go_to_left));}
    else { fprintf(stream, "        s->user_model->trajectory.dist_go_to_left = %.*e;\n", DBL_DECIMAL_DIG - 1, um->trajectory.dist_go_to_left);}
    if (isnan(um->trajectory.dist_go_to_right)) { fprintf(stream, "         s->user_model->trajectory.dist_go_to_right = NAN; \n");}
    else if (isinf(um->trajectory.dist_go_to_right)) { fprintf(stream, "        s->user_model->trajectory.dist_go_to_right = %d * INFINITY; \n", isinf(um->trajectory.dist_go_to_right));}
    else { fprintf(stream, "        s->user_model->trajectory.dist_go_to_right = %.*e;\n", DBL_DECIMAL_DIG - 1, um->trajectory.dist_go_to_right);}
 
    fprintf(stream, "        s->user_model->ground.flag_ground=%d;\n", um->ground.flag_ground);
    fprintf(stream, "        mbs_msg(\"Structure in user model parameter ground.ground_profile must be manually loaded.\\n\");\n");
 
    fprintf(stream, "        mbs_msg(\"Structure in user model parameter utility.sens_IMU must be manually loaded.\\n\");\n");
 
}

// ============================================================ //
 
