# Generated by Django 5.1.4 on 2025-01-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_robmodel_allowed_users_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='robmodel',
            name='graph_config',
            field=models.TextField(blank=True, help_text='JSON string for graph config'),
        ),
    ]
