# Generated by Django 5.1.4 on 2025-01-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_robmodel_graph_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage_title', models.CharField(default='Welcome to Cycloweb', max_length=200)),
                ('homepage_subtitle', models.CharField(default="Quandyga's first web based simulation tool", max_length=500)),
                ('footer_info', models.CharField(default='QuandygaEngeneering', max_length=500)),
            ],
        ),
    ]
